baseURL = "https://example.com"
languageCode = "en-us"
title = "Xiang (Nathan) Qi"
theme = "minimal-light"

[params]
  # Basic Information
  position = "Ph.D. Student"
  affiliation = "[The Hong Kong Polytechnic University](https://www.polyu.edu.hk/)  \n11 Yuk Choi Rd, Hung Hom, Hong Kong"
  email = "nathanxiang.qi@connect.polyu.hk"

  # Search Engine Optimization (SEO)
  keywords = "minimal light"
  description = "A simple and elegant hugo theme for academic personal homepage"
  canonical = "https://minimal-light-theme.yliu.me/"

  # Links
  google_scholar = "https://scholar.google.com/citations?user=CEDTeYoAAAAJ&hl=en"
  cv_link = "https://drive.google.com/file/d/1LgwvIxhYcKiv3AE7JOEcnaIQdjShAFUP/view?usp=sharing"
  linkedin = "www.linkedin.com/in/nathanxiangqi"

  # Images
  avatar = "/img/avatar.png"
  favicon = "/static/img/favicon.png"
  favicon_dark = "/static/img/favicon-dark.png"

  # Other options
  enable_footnote = true
  auto_dark_mode = true
  font = "Serif" # or "Sans Serif"
  google_analytics = "UA-111540567-4"
