baseURL = "https://example.com"
languageCode = "en-us"
title = "Xiang (Nathan) Qi"

[params]
  # Basic Information
  position = "Ph.D. Student"
  affiliation = "PolyU, 12 Yuk Choi Rd, Hung Hom, Hong Kong, China"
  email = "nathanxiang.qi@connect.polyu.hk"

  # Search Engine Optimization (SEO)
  keywords = "minimal light"
  description = "A simple and elegant hugo theme for academic personal homepage"
  canonical = "https://minimal-light-theme.yliu.me/"

  # Links
  google_scholar = "https://scholar.google.com/citations?user=CEDTeYoAAAAJ&hl=en"
  cv_link = "https://drive.google.com/file/d/1Y0_L0EvNQQ4OfYlcVdiYSWeD3sRNdxEF/view?usp=sharing"
  linkedin = "https://www.linkedin.com/in/nathanxiangqi"

  # Images
  avatar = "/img/Nathan.jpg"
  favicon = "/static/img/favicon.png"
  favicon_dark = "/static/img/favicon-dark.png"

  # Other options
  enable_footnote = false
  auto_dark_mode = true
  font = "Serif" # or "Sans Serif"
  google_analytics = ""
